### ISSUE TITLE
t/02-multiple.t is flapping

### ISSUE THREAD

**Issue by AlexDaniel** [CurtTilmes/perl6-epoll#2]
Run it like this:
```bash
while PERL6LIB=lib/ prove --exec=perl6 t/; do :; done
```

```
t/00-meta.t ...... skipped: test: To enable author tests, set AUTHOR_TESTING env var
t/01-simple.t .... ok   
t/02-multiple.t .. 1/10 # Failed test 'No events'
# at t/02-multiple.t line 46
# expected: ''
#      got: 'epoll-event<139763070138088>'
# Looks like you failed 1 test of 10
t/02-multiple.t .. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/10 subtests 

Test Summary Report
-------------------
t/02-multiple.t (Wstat: 256 Tests: 10 Failed: 1)
  Failed test:  10
  Non-zero exit status: 1
Files=3, Tests=16,  1 wallclock secs ( 0.02 usr  0.01 sys +  1.43 cusr  0.16 csys =  1.62 CPU)
Result: FAIL
``

**Comment by AlexDaniel** [comment]
@CurtTilmes ping? :)

**Comment by CurtTilmes** [comment]
epoll is fine, just the test fails.

I was trying to make multiple processes work with it, but I wrote a broken test that seems to occasionally fail.  I'll remove the test and try to figure out a better test.

**Comment by CurtTilmes** [comment]
The test always succeeds on my machine -- I think it is just a timing thing -- I try to send events, then catch them.  I made the test not run by default.

**Comment by AlexDaniel** [comment]
Please reopen. I can still reproduce it in ≈30 runs.

**Comment by AlexDaniel** [comment]
And it still happens.

**Comment by CurtTilmes** [comment]
I had marked the test as extended -- it should not have been run during a normal install, only when explicitly asked to run.  I just removed the test entirely...
